apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bkgrafana
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://192.168.1.10:50615'
  source:
    path: ''
    repoURL: 'https://charts.helm.sh/stable'
    targetRevision: 5.5.6
    chart: grafana
  project: default
